### ISSUE TITLE
Flash migrates old settings

### ISSUE THREAD

**Issue by mathiasvr** [stylesuxx/esc-configurator#109]
With 1 ESC, if I change some settings and press write setup - then flash a firmware file the settings from before the change is migrated back.

**Comment by stylesuxx** [comment]
This specifically only happens when one ESC is attached to the FC?

**Comment by mathiasvr** [comment]
Ah, I thought settings were always read after writing.

**Comment by stylesuxx** [comment]
Yes, the settingsArray is returned, but the settings object was not updated - this is now fixed.
