### ISSUE TITLE
Attributions / Credits missing in the Readme.

### ISSUE THREAD

**Issue by hydra** [stylesuxx/esc-configurator#119]
Can you add attribution / credits / history section the Readme?

Of note this configurator is based on BlHeli-configurator which was based on Cleanflight Configurator which itself was based on Baseflight configurator by CTN.  I note that only BlHeli-configurator is mentioned but the UI contains much of my and other people's work so it seems only fair to acknowledge the key contributors/authors/maintainers of the projects.

e.g. https://github.com/cleanflight/cleanflight-configurator/commit/c3f1c13d54e25b445082bdd1ec432e9875240aa3#diff-4362c7f7032e9687a0a5910cadc127afbe8259b2b941de40dd4246c35b1446f0R220

See also the 'Project History' and 'Authors' section of the CF configurator, here: https://github.com/cleanflight/cleanflight-configurator#authors

**Comment by stylesuxx** [comment]
You are right, I will add a credits section.
