### ISSUE TITLE
Minor state issues on connect

### ISSUE THREAD

**Issue by mathiasvr** [stylesuxx/esc-configurator#151]
I noticed a couple of minor issues that only happens when not really using the app properly, but I will just list them here:

- Pressing disconnect after pressing `read setup` but before reading is done causes a state issue where ESCs are still being read and it's not possible to connect and read them again.
I think maybe disconnect should cancel reading somehow or disconnect should not be allowed while reading setup.

- It's possible to press connect multiple times before it connects causing connection to fail.
Connect should be disabled while a connection attempt is in progress.

**Comment by stylesuxx** [comment]
* [ ] Disable Connect/Disconnect Button while read/write/connect action is in progress
