### ISSUE TITLE
Does not connect with Silverware

### ISSUE THREAD

**Issue by stylesuxx** [stylesuxx/esc-configurator#155]
If FC is flashed with Silverware it will not connect to the configurator.

Potential fix => https://github.com/mathiasvr/esc-configurator/commit/1e0b2f213c572364825c071cd7dff970782d7647

**Comment by stylesuxx** [comment]
@mathiasvr can you tell me with which version of Quicksilver you tested your solution? I flashed the latest (and only) release available via configurator (v0.5.1-dev) and have no issues connecting with esc-configurator at all...

**Comment by mathiasvr** [comment]
I used https://github.com/NotFastEnuf/NFE_QUICKSILVER v1.0

**Comment by stylesuxx** [comment]
Ah, thank you. I only tried to flash what was available in the configurator - can reproduce it now...

**Comment by stylesuxx** [comment]
Alright - for me it seems that the MSP is not properly implemented - even a regression in comparison to the previous version. After sending command `104 - MSP_MOTOR` it seems that the FC resets completely.

I just saw, that this issue is also discussed here => https://github.com/NotFastEnuf/NFE_QUICKSILVER/issues/13

I would prefer to leave the configurator as it is, since in my opinion this should (and from what I understand is already) fixed in firmware.

**Comment by mathiasvr** [comment]
Yes makes sense if MSP reguires implementing the commands so it will work.

**Comment by bkleiner** [comment]
I am sorry about the confusion.

This issue has been fixed in [quicksilver's main repository](https://github.com/BossHobby/QUICKSILVER) please update to the latest version (0.5.1) with the configurator **linked there**

It will probably be some time until the NFE fork catches up.

**Comment by stylesuxx** [comment]
@bkleiner awesome - thank you.
