### ISSUE TITLE
Add support for BlueJay 0.15 versions

### ISSUE THREAD

**Issue by swilkens** [stylesuxx/esc-configurator#163]
**Issue:**
The BLueJay ESC firmware just released V0.15 Test. This version can be flashed, but not yet configured.

https://github.com/mathiasvr/bluejay/releases

**Desired outcome:**
Support for 0.15+ versions of the BlueJay firmware in esc-configurator.

**Comment by stylesuxx** [comment]
Everything is prepared I am only waiting for translations to be confirmed, then I will deploy - might happen in the next couple of hours, latest tomorrow.

**Comment by swilkens** [comment]
That's great news! Thank you for your efforts (and those involved)

**Comment by stylesuxx** [comment]
Added to v0.21.0 release - is now live.
