### ISSUE TITLE
Clarify Flash firmware vs. Write in regard to updating settings

### ISSUE THREAD

**Issue by ShroomzFPV** [stylesuxx/esc-configurator#167]
When trying to change the direction of the motors, it flashes then reverts back to original direction "normal". Attempted multiple times. Please help if possible, thank you!

[esc-configurator-log.txt](https://github.com/stylesuxx/esc-configurator/files/7843992/esc-configurator-log.txt)

**Comment by stylesuxx** [comment]
I am not sure if we talked on Discord. Anyway, I had someone with the same "issue" there. You have to change the motor direction and then click on "Write" in the bottom right - this will write the changed settings.

"Flash All" or "Flash firmware" will flash the firmware with the default settings.

**Comment by ShroomzFPV** [comment]
Wow. I should have picked up on that. Thank you SO much stylesuxx!!!

**Comment by stylesuxx** [comment]
No worries - since two people ran into this issue in short time, I should probably clarify that somewhere in the configurator...
