### ISSUE TITLE
Port already in use by another application - try re-connecting

### ISSUE THREAD

**Issue by nR2Cncdm** [stylesuxx/esc-configurator#168]
I'm using Brave browser on Mac Mini M1 as well as Intel based MacBook Pro, and I'm unable to connect to my Beebrain BL V3 drone. The log states "Port already in use by another application - try re-connecting".
![image](https://user-images.githubusercontent.com/60517584/148904640-9f03d8f6-75f6-46c4-b35c-a754692b1060.png)

**Comment by stylesuxx** [comment]
Brave browser does not support Web Serial unfortunately. They disabled the functionality completely, relevant issue is here => https://github.com/brave/brave-browser/issues/13902

There is nothing I can do on my side. If you don't want to use Google Chrome, you might want to try Vivaldi - also Chromium based and does support the Web serial API. As a last resort you could also try the downloadable app from here https://github.com/mathiasvr/esc-configurator-app

**Comment by nR2Cncdm** [comment]
Thanks for the quick reply. I’ll try a different browser.
