### ISSUE TITLE
betafpv f4 1s ELRS 2.4g v2.0 flight controller

### ISSUE THREAD

**Issue by mostafayo** [stylesuxx/esc-configurator#172]
after flashing bluejay on the AIO FC betafpv f4 1s ELRS 2.4g v2.0 the motor did not spin even after increasing the startup power to the max only 2 motor of 4 are spinning

**Comment by stylesuxx** [comment]
Please report this in either the Bluejay Discord or The [Bluejay repository](https://github.com/mathiasvr/bluejay) since this is not really an issue with the configurator.

**Comment by stylesuxx** [comment]
Also I am wondering - was this after enabling bi-directional DSHOT?

**Comment by stylesuxx** [comment]
Hey @mostafayo any more input on this issue, otherwise I will close it.

**Comment by stylesuxx** [comment]
Closing this due to lack of information, feel free to re-open with needed information.
