### ISSUE TITLE
"Port already in use by another application - try re-connecting"

### ISSUE THREAD

**Issue by guilleortas** [stylesuxx/esc-configurator#178]
Hi there, I can't find the "Save Debug Log" button, so I will provide an explanation of the issue instead.
My drivers are completely fine and I can access my ESC settings on the legacy Bluejay configurator standalone app or my Betaflight setting using the regular BF configurator.
The issue is that after allowing access to my COM port (yes, I triple-checked it's the correct one), ESC Configurator just prints a line in the log saying "Port already in use by another application - try re-connecting".
I'm attaching a screen capture so you can see exactly what's going on:
https://filetransfer.io/data-package/9wuZTMDG

Do you have any idea what could be happening?

**Comment by mathiasvr** [comment]
Did you install PWA with brave?

Brave browser is not supported so you will need to use chrome/edge or install the standalone version.

**Comment by DireCat** [comment]
Confirm the issue with Brave browser (no plugins, shields off). Get the same error "Port already in use ..." on Win10 and doesn't see any COM port on Win7, but works fine with Chromium portable.

**Comment by guilleortas** [comment]
@mathiasvr indeed, confirmed to be working flawlessly on edge
Seems like brave just doesn't support PWAs by default

**Comment by stylesuxx** [comment]
> @mathiasvr indeed, confirmed to be working flawlessly on edge Seems like brave just doesn't support PWAs by default

The problem is, that Brave removed the functionality for web serial, not that they don't support PWAs...

**Comment by guilleortas** [comment]
Ah, that's great to know, thanks!
Nothing wrong with ESC Configurator then 👌🏻
