### ISSUE TITLE
Control LED lights on supported ESCs via DSHOT command

### ISSUE THREAD

**Issue by Linjieqiang** [stylesuxx/esc-configurator#182]

**Comment by stylesuxx** [comment]
Not sure what exactly you mean? LEDs are configured through Betaflight. There are some ESCs with LEDs, but as far as I know you can't configure them. If so, could you link me to such a product?

**Comment by stylesuxx** [comment]
Summoning @mathiasvr - can this be configured with Bluejay?

@Linjieqiang unfortunately I have never seen such an ESC - could you link me to the product please? Could you make a screenshot of how this is being configured with the BLHeli_S configurator?

**Comment by Linjieqiang** [comment]
![image](https://user-images.githubusercontent.com/10217966/150377202-e6669413-26c0-4a5f-b26d-75a5167a5aa8.png)
![image](https://user-images.githubusercontent.com/10217966/150377240-2ba68876-3640-40ef-a550-581dda4015ad.png)
![image](https://user-images.githubusercontent.com/10217966/150377252-bdfaab99-7a0f-490b-b5cd-22f48dc0181f.png)

**Comment by stylesuxx** [comment]
Which layout do they use exactly? Please also post a link to the actual product and the screenshot from BLHeli_S configurator.

**Comment by Linjieqiang** [comment]
![image](https://user-images.githubusercontent.com/10217966/150378667-7f489bd9-989a-4482-99a1-187d6273b4fc.png)

such as https://www.rc-wing.com/30a-bheli-s-esc-dshot.html

**Comment by Linjieqiang** [comment]
Nice.

**Comment by mathiasvr** [comment]
In original BLHeli_S it seems its only possible to turn the LED on and off, and only using configurator - DShot LED commands are not implemented. How are you configuring them with BLHeli_S configurator? I cannot see any way to use the RGB feature with the current code, but it might be possible to implement.

**Comment by Linjieqiang** [comment]
This is actually an idea of ​​mine, because my ESC hardware has led lights, but I can't find a way to turn it on.
