### ISSUE TITLE
Cannot Flash ESC that Have JFLIGHT Firmware Installed

### ISSUE THREAD

**Issue by avella007** [stylesuxx/esc-configurator#190]
Found that both the BlueJ App Configurator and the BlueJ Web based Configurator will not allow you to flash BlueJ ESC on my motors that have JFLIGHT 3.2 flashed.  

I tried to use the BlueJ Web Based Configurator to see if I could flash the Bheli_S first and then the BlueJ, but the configurator messed up my RSCs and I had to go back to FFLIGHT to refash the ESCs.

**Comment by stylesuxx** [comment]
We would need some information to be actually able to help you. What does "messed up" mean? Which operating system are you on? Can you post the logs from the configurator? Which ESCs are you using?

Generally there are no issues of flashing over JESC...

**Comment by stylesuxx** [comment]
Closing this down due to lack of information, feel free to re-open with the requested information.
