### ISSUE TITLE
Please promote option "Show firmware pre-releases" for BlueJay to master

### ISSUE THREAD

**Issue by howels** [stylesuxx/esc-configurator#195]
Looks like the BlueJay option "Show firmware pre-releases" was added but not moved to master yet. 

Well, BlueJay has added a release that requires this option now! (https://github.com/mathiasvr/bluejay/releases/tag/test-melody-pwm)

So please promote this new option to master if it is working. Thanks!

**Comment by stylesuxx** [comment]
New version is in preparation. You can join discord and test my local build of the upcoming version. Until I have a couple more people come back that the test version is working for them, and I had the time to run through the test protocol I can not publish a new release.

**Comment by mathiasvr** [comment]
Yeah sorry that test got published a bit too soon, but would be great if we can also test esc configurator at the same time.

**Comment by stylesuxx** [comment]
Yeah, there have been so many changes lately that I simply could not keep up with testing at all. Unfortunately neither did the people I usually rely on. For the future I am planning to have  some way to at least access the develop builds in some way.

**Comment by howels** [comment]
Working in testing build :+1:
