### ISSUE TITLE
Bluejay version '0.16' (Layout 204) is not yet supported.

### ISSUE THREAD

**Issue by pfreundl** [stylesuxx/esc-configurator#206]
Got this Error after flashing my jhemcu f405aio (non pro) to 0.16 

thank you

here is the debug log:

2021/10/29 19:16:15: Port selected
2021/10/29 19:16:18: Opened serial port
2021/10/29 19:16:18: MultiWii API version received: 1.43.0
2021/10/29 19:16:18: Flight controller info, identifier: BTFL version: 4.2.0
2021/10/29 19:16:18: Running firmware released on: Jun 14 2020 03:05:26
2021/10/29 19:16:18: Board: S7X2, version: 0
2021/10/29 19:16:18: Unique device ID received - 0x0270037465350152030364e
2021/10/29 19:16:28: Trying to read 4 ESCs
2021/10/29 19:16:28: Read ESC 1: G-H-30 - Bluejay (BETA), 0.14, 48kHz
2021/10/29 19:16:28: Read ESC 2: G-H-30 - Bluejay (BETA), 0.14, 48kHz
2021/10/29 19:16:28: Read ESC 3: G-H-30 - Bluejay (BETA), 0.14, 48kHz
2021/10/29 19:16:29: Read ESC 4: G-H-30 - Bluejay (BETA), 0.14, 48kHz
2021/10/29 19:16:29: Done reading ESCs
2021/10/29 19:16:58: Chosen firmware: https://github.com/mathiasvr/bluejay/releases/download/v0.14/G_H_30_48_v0.14.hex 
2021/10/29 19:16:58: Fetching firmware from repository 
2021/10/29 19:16:59: Saved file to local storage 
2021/10/29 19:16:59: Flashing ESC 1
2021/10/29 19:17:09: Flashed ESC 1 - 10.8s
2021/10/29 19:17:10: Bluejay layout found 
2021/10/29 19:17:10: Migrated setting STARTUP_POWER_MIN 
2021/10/29 19:17:10: Migrated setting DITHERING 
2021/10/29 19:17:10: Migrated setting STARTUP_POWER_MAX 
2021/10/29 19:17:10: Migrated setting RPM_POWER_SLOPE 
2021/10/29 19:17:10: Migrated setting MOTOR_DIRECTION 
2021/10/29 19:17:10: Migrated setting COMMUTATION_TIMING 
2021/10/29 19:17:10: Migrated setting BEEP_STRENGTH 
2021/10/29 19:17:10: Migrated setting BEACON_STRENGTH 
2021/10/29 19:17:10: Migrated setting BEACON_DELAY 
2021/10/29 19:17:10: Migrated setting DEMAG_COMPENSATION 
2021/10/29 19:17:10: Migrated setting TEMPERATURE_PROTECTION 
2021/10/29 19:17:10: Migrated setting BRAKE_ON_STOP 
2021/10/29 19:17:10: Migrated setting STARTUP_MELODY 
2021/10/29 19:17:10: No changes - not updating ESC 1
2021/10/29 19:17:10: Flashing ESC 2
2021/10/29 19:17:21: Flashed ESC 2 - 10.7s
2021/10/29 19:17:21: Bluejay layout found 
2021/10/29 19:17:21: Migrated setting STARTUP_POWER_MIN 
2021/10/29 19:17:21: Migrated setting DITHERING 
2021/10/29 19:17:21: Migrated setting STARTUP_POWER_MAX 
2021/10/29 19:17:21: Migrated setting RPM_POWER_SLOPE 
2021/10/29 19:17:21: Migrated setting MOTOR_DIRECTION 
2021/10/29 19:17:21: Migrated setting COMMUTATION_TIMING 
2021/10/29 19:17:21: Migrated setting BEEP_STRENGTH 
2021/10/29 19:17:21: Migrated setting BEACON_STRENGTH 
2021/10/29 19:17:21: Migrated setting BEACON_DELAY 
2021/10/29 19:17:21: Migrated setting DEMAG_COMPENSATION 
2021/10/29 19:17:21: Migrated setting TEMPERATURE_PROTECTION 
2021/10/29 19:17:21: Migrated setting BRAKE_ON_STOP 
2021/10/29 19:17:21: Migrated setting STARTUP_MELODY 
2021/10/29 19:17:21: No changes - not updating ESC 2
2021/10/29 19:17:21: Flashing ESC 3
2021/10/29 19:17:32: Flashed ESC 3 - 10.7s
2021/10/29 19:17:32: Bluejay layout found 
2021/10/29 19:17:32: Migrated setting STARTUP_POWER_MIN 
2021/10/29 19:17:32: Migrated setting DITHERING 
2021/10/29 19:17:32: Migrated setting STARTUP_POWER_MAX 
2021/10/29 19:17:32: Migrated setting RPM_POWER_SLOPE 
2021/10/29 19:17:32: Migrated setting MOTOR_DIRECTION 
2021/10/29 19:17:32: Migrated setting COMMUTATION_TIMING 
2021/10/29 19:17:32: Migrated setting BEEP_STRENGTH 
2021/10/29 19:17:32: Migrated setting BEACON_STRENGTH 
2021/10/29 19:17:32: Migrated setting BEACON_DELAY 
2021/10/29 19:17:32: Migrated setting DEMAG_COMPENSATION 
2021/10/29 19:17:32: Migrated setting TEMPERATURE_PROTECTION 
2021/10/29 19:17:32: Migrated setting BRAKE_ON_STOP 
2021/10/29 19:17:32: Migrated setting STARTUP_MELODY 
2021/10/29 19:17:32: No changes - not updating ESC 3
2021/10/29 19:17:32: Flashing ESC 4
2021/10/29 19:17:43: Flashed ESC 4 - 10.7s
2021/10/29 19:17:43: Bluejay layout found 
2021/10/29 19:17:43: Migrated setting STARTUP_POWER_MIN 
2021/10/29 19:17:43: Migrated setting DITHERING 
2021/10/29 19:17:43: Migrated setting STARTUP_POWER_MAX 
2021/10/29 19:17:43: Migrated setting RPM_POWER_SLOPE 
2021/10/29 19:17:43: Migrated setting MOTOR_DIRECTION 
2021/10/29 19:17:43: Migrated setting COMMUTATION_TIMING 
2021/10/29 19:17:43: Migrated setting BEEP_STRENGTH 
2021/10/29 19:17:43: Migrated setting BEACON_STRENGTH 
2021/10/29 19:17:43: Migrated setting BEACON_DELAY 
2021/10/29 19:17:43: Migrated setting DEMAG_COMPENSATION 
2021/10/29 19:17:43: Migrated setting TEMPERATURE_PROTECTION 
2021/10/29 19:17:43: Migrated setting BRAKE_ON_STOP 
2021/10/29 19:17:43: Migrated setting STARTUP_MELODY 
2021/10/29 19:17:43: No changes - not updating ESC 4
2021/10/29 19:18:31: Updating ESC 1 - finished
2021/10/29 19:18:31: Updating ESC 2 - finished
2021/10/29 19:18:32: Updating ESC 3 - finished
2021/10/29 19:18:32: Updating ESC 4 - finished
2021/10/29 19:18:47: Closed port
2021/10/29 19:18:52: Unplugged
2021/11/01 23:46:39: Plugged in
2021/11/01 23:46:47: Opened serial port
2021/11/01 23:46:48: MultiWii API version received: 1.43.0
2021/11/01 23:46:48: Flight controller info, identifier: BTFL version: 4.2.10
2021/11/01 23:46:48: Running firmware released on: Sep 30 2021 11:31:52
2021/11/01 23:46:48: Board: S7X2, version: 0
2021/11/01 23:46:48: Unique device ID received - 0x0270037465350152030364e
2021/11/01 23:47:27: Closed port
2021/11/01 23:48:13: Opened serial port
2021/11/01 23:48:13: MultiWii API version received: 1.43.0
2021/11/01 23:48:13: Flight controller info, identifier: BTFL version: 4.2.10
2021/11/01 23:48:13: Running firmware released on: Sep 30 2021 11:31:52
2021/11/01 23:48:13: Board: S7X2, version: 0
2021/11/01 23:48:13: Unique device ID received - 0x0270037465350152030364e
2021/11/01 23:48:18: Trying to read 4 ESCs
2021/11/01 23:48:19: Read ESC 1: G-H-30 - Bluejay (BETA), 0.14, 48kHz
2021/11/01 23:48:19: Read ESC 2: G-H-30 - Bluejay (BETA), 0.14, 48kHz
2021/11/01 23:48:19: Read ESC 3: G-H-30 - Bluejay (BETA), 0.14, 48kHz
2021/11/01 23:48:19: Read ESC 4: G-H-30 - Bluejay (BETA), 0.14, 48kHz
2021/11/01 23:48:19: Done reading ESCs
2021/11/01 23:48:31: Updating ESC 1 - finished
2021/11/01 23:48:31: Updating ESC 2 - finished
2021/11/01 23:48:31: No changes - not updating ESC 3
2021/11/01 23:48:31: No changes - not updating ESC 4
2021/11/01 23:48:42: Closed port
2021/11/01 23:48:44: Opened serial port
2021/11/01 23:48:44: MultiWii API version received: 1.43.0
2021/11/01 23:48:44: Flight controller info, identifier: BTFL version: 4.2.10
2021/11/01 23:48:44: Running firmware released on: Sep 30 2021 11:31:52
2021/11/01 23:48:44: Board: S7X2, version: 0
2021/11/01 23:48:44: Unique device ID received - 0x0270037465350152030364e
2021/11/01 23:49:05: Closed port
2021/11/01 23:49:06: Opened serial port
2021/11/01 23:49:06: MultiWii API version received: 1.43.0
2021/11/01 23:49:06: Flight controller info, identifier: BTFL version: 4.2.10
2021/11/01 23:49:06: Running firmware released on: Sep 30 2021 11:31:52
2021/11/01 23:49:06: Board: S7X2, version: 0
2021/11/01 23:49:06: Unique device ID received - 0x0270037465350152030364e
2021/11/01 23:49:11: Closed port
2021/11/07 13:31:56: Port selected
2021/11/07 13:31:59: Opened serial port
2021/11/07 13:31:59: MultiWii API version received: 1.43.0
2021/11/07 13:31:59: Flight controller info, identifier: BTFL version: 4.2.0
2021/11/07 13:31:59: Running firmware released on: Jun 14 2020 03:04:22
2021/11/07 13:31:59: Board: S405, version: 0
2021/11/07 13:31:59: Unique device ID received - 0x03400503535510738353732
2021/11/07 13:32:08: Trying to read 4 ESCs
2021/11/07 13:32:09: Read ESC 1: G-H-30 - BLHeli_S, 16.7
2021/11/07 13:32:11: Read ESC 2: G-H-30 - BLHeli_S, 16.7
2021/11/07 13:32:12: Read ESC 3: G-H-30 - BLHeli_S, 16.7
2021/11/07 13:32:13: Read ESC 4: G-H-30 - BLHeli_S, 16.7
2021/11/07 13:32:13: Done reading ESCs
2021/11/07 13:32:35: Chosen firmware: https://github.com/mathiasvr/bluejay/releases/download/v0.14/G_H_30_48_v0.14.hex 
2021/11/07 13:32:35: Got firmware from local storage 
2021/11/07 13:32:35: Flashing ESC 1
2021/11/07 13:32:47: Flashed ESC 1 - 11.3s
2021/11/07 13:32:47: Flashing ESC 2
2021/11/07 13:32:58: Flashed ESC 2 - 11.2s
2021/11/07 13:32:58: Flashing ESC 3
2021/11/07 13:33:10: Flashed ESC 3 - 11.2s
2021/11/07 13:33:10: Flashing ESC 4
2021/11/07 13:33:21: Flashed ESC 4 - 11.1s
2021/11/07 13:34:16: Updating ESC 1 - finished
2021/11/07 13:34:17: Updating ESC 2 - finished
2021/11/07 13:34:17: Updating ESC 3 - finished
2021/11/07 13:34:17: Updating ESC 4 - finished
2021/11/07 13:34:35: Closed port
2021/11/07 14:19:48: Plugged in
2021/11/07 14:19:50: Could not open serial port 
2021/11/07 14:19:50: Error: Could not open serial port 
2021/11/07 14:19:50: Port already in use by another application - try re-connecting
2021/11/07 14:20:19: Plugged in
2021/11/07 14:20:21: Could not open serial port 
2021/11/07 14:20:21: Error: Could not open serial port 
2021/11/07 14:20:21: Port already in use by another application - try re-connecting
2021/11/07 14:20:26: Unplugged
2021/11/07 14:20:29: Plugged in
2021/11/07 14:20:33: Plugged in
2021/11/07 14:20:34: Opened serial port
2021/11/07 14:20:34: MultiWii API version received: 1.42.0
2021/11/07 14:20:34: Flight controller info, identifier: BTFL version: 4.1.4
2021/11/07 14:20:34: Running firmware released on: Feb  4 2020 17:26:13
2021/11/07 14:20:34: Board: S411, version: 0
2021/11/07 14:20:34: Unique device ID received - 0x02e002e3337511038373732
2021/11/07 14:20:50: Trying to read 4 ESCs
2021/11/07 14:20:51: Read ESC 1: G-H-30 - BLHeli_S, 16.7
2021/11/07 14:20:52: Read ESC 2: G-H-30 - BLHeli_S, 16.7
2021/11/07 14:20:54: Read ESC 3: G-H-30 - BLHeli_S, 16.7
2021/11/07 14:20:55: Read ESC 4: G-H-30 - BLHeli_S, 16.7
2021/11/07 14:20:55: Done reading ESCs
2021/11/07 14:21:16: Chosen firmware: https://github.com/mathiasvr/bluejay/releases/download/v0.14/G_H_30_24_v0.14.hex 
2021/11/07 14:21:16: Fetching firmware from repository 
2021/11/07 14:21:17: Saved file to local storage 
2021/11/07 14:21:17: Flashing ESC 1
2021/11/07 14:21:28: Flashed ESC 1 - 11.5s
2021/11/07 14:21:29: Flashing ESC 2
2021/11/07 14:21:40: Flashed ESC 2 - 11.5s
2021/11/07 14:21:41: Flashing ESC 3
2021/11/07 14:21:52: Flashed ESC 3 - 11.5s
2021/11/07 14:21:53: Flashing ESC 4
2021/11/07 14:22:04: Flashed ESC 4 - 11.5s
2021/11/07 14:22:10: Closed port
2021/11/07 14:22:15: Opened serial port
2021/11/07 14:22:15: MultiWii API version received: 1.42.0
2021/11/07 14:22:15: Flight controller info, identifier: BTFL version: 4.1.4
2021/11/07 14:22:15: Running firmware released on: Feb  4 2020 17:26:13
2021/11/07 14:22:15: Board: S411, version: 0
2021/11/07 14:22:15: Unique device ID received - 0x02e002e3337511038373732
2021/11/07 14:22:19: Trying to read 4 ESCs
2021/11/07 14:22:19: Read ESC 1: G-H-30 - Bluejay (BETA), 0.14, 24kHz
2021/11/07 14:22:19: Read ESC 2: G-H-30 - Bluejay (BETA), 0.14, 24kHz
2021/11/07 14:22:20: Read ESC 3: G-H-30 - Bluejay (BETA), 0.14, 24kHz
2021/11/07 14:22:20: Read ESC 4: G-H-30 - Bluejay (BETA), 0.14, 24kHz
2021/11/07 14:22:20: Done reading ESCs
2021/11/07 14:23:33: Updating ESC 1 - finished
2021/11/07 14:23:34: Updating ESC 2 - finished
2021/11/07 14:23:34: Updating ESC 3 - finished
2021/11/07 14:23:35: Updating ESC 4 - finished
2021/11/07 14:23:42: Closed port
2021/11/07 18:11:15: Plugged in
2021/11/07 18:11:16: Opened serial port
2021/11/07 18:11:16: MultiWii API version received: 1.42.0
2021/11/07 18:11:16: Flight controller info, identifier: BTFL version: 4.1.4
2021/11/07 18:11:17: Running firmware released on: Feb  4 2020 17:26:13
2021/11/07 18:11:17: Board: S411, version: 0
2021/11/07 18:11:17: Unique device ID received - 0x02e002e3337511038373732
2021/11/07 18:12:11: Trying to read 4 ESCs
2021/11/07 18:12:12: Read ESC 1: G-H-30 - Bluejay (BETA), 0.14, 24kHz
2021/11/07 18:12:12: Read ESC 2: G-H-30 - Bluejay (BETA), 0.14, 24kHz
2021/11/07 18:12:12: Read ESC 3: G-H-30 - Bluejay (BETA), 0.14, 24kHz
2021/11/07 18:12:12: Read ESC 4: G-H-30 - Bluejay (BETA), 0.14, 24kHz
2021/11/07 18:12:12: Done reading ESCs
2021/11/07 18:12:24: No changes - not updating ESC 1
2021/11/07 18:12:24: Updating ESC 2 - finished
2021/11/07 18:12:25: Updating ESC 3 - finished
2021/11/07 18:12:25: No changes - not updating ESC 4
2021/11/07 18:12:38: Closed port
2021/11/07 18:12:39: Opened serial port
2021/11/07 18:12:39: MultiWii API version received: 1.42.0
2021/11/07 18:12:39: Flight controller info, identifier: BTFL version: 4.1.4
2021/11/07 18:12:39: Running firmware released on: Feb  4 2020 17:26:13
2021/11/07 18:12:39: Board: S411, version: 0
2021/11/07 18:12:39: Unique device ID received - 0x02e002e3337511038373732
2021/11/07 18:13:02: Closed port
2021/12/17 18:28:46: Plugged in
2021/12/17 18:28:55: Opened serial port
2021/12/17 18:28:55: MultiWii API version received: 1.42.0
2021/12/17 18:28:55: Flight controller info, identifier: BTFL version: 4.1.7
2021/12/17 18:28:55: Running firmware released on: Sep 26 2020 16:25:01
2021/12/17 18:28:55: Board: FY4O, version: 0
2021/12/17 18:28:55: Unique device ID received - 0x03d002f3436510d35373636
2021/12/17 18:29:45: Trying to read 4 ESCs
2021/12/17 18:29:46: Read ESC 1: G-H-30 - BLHeli_S, 16.7
2021/12/17 18:29:47: Read ESC 2: G-H-30 - BLHeli_S, 16.7
2021/12/17 18:29:48: Read ESC 3: G-H-30 - BLHeli_S, 16.7
2021/12/17 18:29:49: Read ESC 4: G-H-30 - BLHeli_S, 16.7
2021/12/17 18:29:49: Done reading ESCs
2021/12/17 18:30:10: Chosen firmware: https://github.com/mathiasvr/bluejay/releases/download/v0.14/G_H_30_48_v0.14.hex 
2021/12/17 18:30:10: Got firmware from local storage 
2021/12/17 18:30:10: Flashing ESC 1
2021/12/17 18:30:21: Flashed ESC 1 - 11.3s
2021/12/17 18:30:21: Flashing ESC 2
2021/12/17 18:30:33: Flashed ESC 2 - 11.4s
2021/12/17 18:30:33: Flashing ESC 3
2021/12/17 18:30:44: Flashed ESC 3 - 11.4s
2021/12/17 18:30:45: Flashing ESC 4
2021/12/17 18:30:56: Flashed ESC 4 - 11.4s
2021/12/17 18:38:38: Updating ESC 1 - finished
2021/12/17 18:38:39: Updating ESC 2 - finished
2021/12/17 18:38:39: Updating ESC 3 - finished
2021/12/17 18:38:40: Updating ESC 4 - finished
2021/12/17 18:38:53: No changes - not updating ESC 1
2021/12/17 18:38:53: No changes - not updating ESC 2
2021/12/17 18:38:53: No changes - not updating ESC 3
2021/12/17 18:38:53: No changes - not updating ESC 4
2021/12/17 18:38:58: Closed port
2021/12/17 18:39:39: Unplugged
2021/12/17 18:47:17: Plugged in
2021/12/17 18:47:19: Could not open serial port 
2021/12/17 18:47:19: Error: Could not open serial port 
2021/12/17 18:47:19: Port already in use by another application - try re-connecting
2021/12/17 18:47:37: Plugged in
2021/12/17 18:47:38: Opened serial port
2021/12/17 18:47:38: MultiWii API version received: 1.42.0
2021/12/17 18:47:38: Flight controller info, identifier: BTFL version: 4.1.7
2021/12/17 18:47:38: Running firmware released on: Sep 26 2020 16:25:01
2021/12/17 18:47:38: Board: FY4O, version: 0
2021/12/17 18:47:38: Unique device ID received - 0x03d002f3436510d35373636
2021/12/17 18:47:42: Trying to read 4 ESCs
2021/12/17 18:47:43: Read ESC 1: G-H-30 - Bluejay (BETA), 0.14, 48kHz
2021/12/17 18:47:43: Read ESC 2: G-H-30 - Bluejay (BETA), 0.14, 48kHz
2021/12/17 18:47:43: Read ESC 3: G-H-30 - Bluejay (BETA), 0.14, 48kHz
2021/12/17 18:47:43: Read ESC 4: G-H-30 - Bluejay (BETA), 0.14, 48kHz
2021/12/17 18:47:43: Done reading ESCs
2021/12/17 18:47:51: No changes - not updating ESC 1
2021/12/17 18:47:51: No changes - not updating ESC 2
2021/12/17 18:47:51: Updating ESC 3 - finished
2021/12/17 18:47:51: No changes - not updating ESC 4
2021/12/17 18:47:54: Closed port
2021/12/17 18:49:03: Unplugged
2021/12/17 18:49:05: Plugged in
2022/01/28 23:59:08: Plugged in
2022/01/28 23:59:12: Opened serial port
2022/01/28 23:59:12: MultiWii API version received: 1.44.0
2022/01/28 23:59:12: Flight controller info, identifier: BTFL version: 4.3.0
2022/01/28 23:59:12: Running firmware released on: Jan  9 2022 11:40:24
2022/01/28 23:59:12: Board: S405, version: 0
2022/01/28 23:59:12: Unique device ID received - 0x03400503535510738353732
2022/01/28 23:59:20: Trying to read 4 ESCs
2022/01/28 23:59:20: Read ESC 1: G-H-30 - Bluejay (BETA), 0.14, 48kHz
2022/01/28 23:59:20: Read ESC 2: G-H-30 - Bluejay (BETA), 0.14, 48kHz
2022/01/28 23:59:20: Read ESC 3: G-H-30 - Bluejay (BETA), 0.14, 48kHz
2022/01/28 23:59:21: Read ESC 4: G-H-30 - Bluejay (BETA), 0.14, 48kHz
2022/01/28 23:59:21: Done reading ESCs
2022/01/28 23:59:55: Chosen firmware: https://github.com/mathiasvr/bluejay/releases/download/v0.16/G_H_30_24_v0.16.hex 
2022/01/28 23:59:55: Fetching firmware from repository 
2022/01/28 23:59:56: Saved file to local storage 
2022/01/28 23:59:56: Flashing ESC 1
2022/01/29 00:00:07: Flashed ESC 1 - 11.5s
2022/01/29 00:00:08: Layout revision 204 is not yet supported
2022/01/29 00:00:08: Flashing ESC 2
2022/01/29 00:00:19: Flashed ESC 2 - 11.3s
2022/01/29 00:00:19: Layout revision 204 is not yet supported
2022/01/29 00:00:19: Flashing ESC 3
2022/01/29 00:00:30: Flashed ESC 3 - 11.3s
2022/01/29 00:00:31: Layout revision 204 is not yet supported
2022/01/29 00:00:31: Flashing ESC 4
2022/01/29 00:00:42: Flashed ESC 4 - 11.2s
2022/01/29 00:00:42: Layout revision 204 is not yet supported

**Comment by stylesuxx** [comment]
Which version is shown to you on the bottom right of the configurator? Seems like you still have an old version cached... You should try a forced reload - Shift + F5

**Comment by pfreundl** [comment]
that might have been the problem, now it works :) thank you! also i just found this great nokia melody (credit to spaghetti_hands on yt) and converted it to RTTTL:
melody:b=240,o=5,d=4:8e6,8d6,f#,g#,8c#6,8b,d,e,8b,8a,c#,e,2a
