### ISSUE TITLE
Lost ESC 1 on a CrazyBeeF3FR while flashing blue jay...

### ISSUE THREAD

**Issue by docjeffrey** [stylesuxx/esc-configurator#229]
I was flashing Blue Jay 0.14 on this board from 16.7 on my Mac and it froze flashing ESC1 i waited for almost 10min nothing happened so i unplugged and plugged it says failed to read ESC 1 and now it is not showing up when I plug and read setup...

What can i do to flash back ESC 1 to BL Heli 16.7 O-L-5... I will not arm the quad until i have this fixed... do you know any software i can use?

**Comment by stylesuxx** [comment]
Please post the log.

Does the ESC show up as Unknown, or does it not show up at all?

**Comment by alexagv** [comment]
Same happened to me. Brand new Mamba F35, I'm also running macOS. ESC1 flashed fine then it hung on ESC2 forever. I unplugged and tried again. This time ESC1 failed. Now ESC1 is missing, ESC2 is corrupt and wont flash :( 

Nothing in the logs, just said "Flashing ESC2"...

**Comment by alexagv** [comment]
My log after reading setup in current (broken) state:
[esc-configurator-log.txt](https://github.com/stylesuxx/esc-configurator/files/8449265/esc-configurator-log.txt)

**Comment by alexagv** [comment]
Log from macOS
[esc-configurator-log (1).txt](https://github.com/stylesuxx/esc-configurator/files/8449332/esc-configurator-log.1.txt)
S

**Comment by docjeffrey** [comment]
Hello Sir Stylesuxx... 
The ESC #1 does not show up anymore... Im trying to reflash using Arduino nano... how ever im using an old mac... and BL Heli Suite only runs on windows ill be going to my friends place for the windows OS... the rest of the ESCs are on BLHeli 16.7 its the most stable firmware that has no desyncs and flies good... tried 16.9 - i have series of desyncs almost always... thank you sir...

**Comment by docjeffrey** [comment]
Log from my failed flash...

[CrazyBee F3FR esc-configurator-log.txt](https://github.com/stylesuxx/esc-configurator/files/8472822/CrazyBee.F3FR.esc-configurator-log.txt)
