### ISSUE TITLE
connection problem am32

### ISSUE THREAD

**Issue by dex1968** [stylesuxx/esc-configurator#235]
Port already in use by another application - try re-connecting

**Comment by dex1968** [comment]
2022-04-23 @ 00:32:25 -- Port already in use by another application - try re-connecting
2022-04-23 @ 00:32:24 -- Opened serial port
2022-04-23 @ 00:32:22 -- Port selected
2022-04-23 @ 00:31:40 -- Plugged in
2022-04-23 @ 00:25:13 -- Chrome (100.0.4896.127) on Windows

**Comment by stylesuxx** [comment]
Could you please provide some more information:
* Which FC?
* Which Version of Windows?
* Are all other configurators closed?
* Can you connect via Betaflight Connfigurator?

**Comment by dex1968** [comment]
good morning.
esc Hackrc 35a, changed bootloader "if I did the job right with cube32st"
arduino nano "configured with Blheli_32" two wires
windows 7
now that I changed the bootloader with the Blheli_32 configurator it no longer connects to the esc via arduino nano.
thanks for the help
Francis

**Comment by stylesuxx** [comment]
Hey @dex1968 the configurator only supports flashing via Betaflight pass-through, so you will need an FC. alternative is to use the "native" AM32 configurator.

**Comment by dex1968** [comment]
stlink?

**Comment by stylesuxx** [comment]
No, ESC Configurator ONLY works with BF passthrough.

**Comment by dex1968** [comment]
ok.with FC and passthrough it works.
pity not to be able to use other for single esc.
