### ISSUE TITLE
BLHeli32 to RTTTL conversion

### ISSUE THREAD

**Issue by stylesuxx** [stylesuxx/esc-configurator#244]
Use https://github.com/Globolo001/BLHELI_32_to_RTTTL to automatically convert BLHeli32 tunes to RTTTL, add some info about the editor being capable of that.

**Comment by ltwin8** [comment]
> Use https://github.com/Globolo001/BLHELI_32_to_RTTTL to automatically convert BLHeli32 tunes to RTTTL, add some info about the editor being capable of that.

Could you please give an example maybe based on the song in videos description? Like the variables octave, length, interval… I can not find octave…

https://youtu.be/CqF1gtB6Txg?feature=shared

best regards

**Comment by stylesuxx** [comment]
You should probably ask the creator of the converter. I have no idea about Blheli32 data structures at all.

**Comment by stylesuxx** [comment]
Closing since BLHeli32 is no longer a thing.
