### ISSUE TITLE
FC Betafpv f411rx v1.2 icm20689

### ISSUE THREAD

**Issue by MikeFPV75** [stylesuxx/esc-configurator#246]
Hola, en esta controladora, al flashear esc bluejay 0.16 96khz los motores no arrancan correctamente al armar. Un saludo y gracias.

**Comment by MikeFPV75** [comment]
con esc blheliM jazzmaverick funciona bien poniendo startup 1.0

**Comment by stylesuxx** [comment]
English please. Try increasing min/max startup power if the motors don't spin.

**Comment by stylesuxx** [comment]
Closing for lack of further information, seems to be rather a Bluejay issue than a configurator issue anyway.
