### ISSUE TITLE
TWO MOTORS NOT RESPONDING AFTER JESC FLASH

### ISSUE THREAD

**Issue by JORTIZEE** [stylesuxx/esc-configurator#264]
Hello, I recently flashed my drones with the JESC conf and the very last drone that I had flashed two of the motors are not responding.  The JESC configurator is not seeing all 4 of the motors, it did show all of them when I first flashed.  Can you please advise? Thank you.

**Comment by stylesuxx** [comment]
Not sure why you are coming here with JESC problems? esc-configurator.com does not support JESC in any way.

That being said, if two ESCs are not showing you might need to re-flash them via C2 interface. In case you have your radio connected during flashing/reading, disable it. Radio link is known to mess with the flashing process in certain cases. You can see if esc-configurator.com is showing all your ESC's - technically you could try to then reset them back to BLHeli_S and try reflashing with JESC

Again, I can not give any advice here in regards to JESC though.
