### ISSUE TITLE
Custom Logo

### ISSUE THREAD

**Issue by stylesuxx** [stylesuxx/esc-configurator#27]
@Noctaro is designing a Logo, since the Bluejay Logo does not really represent the project as a whole.

**Comment by mathiasvr** [comment]
![sadjay](https://user-images.githubusercontent.com/8664776/111240757-1d043580-85fc-11eb-9e15-ac29e2213097.png)

**Comment by stylesuxx** [comment]
I really like the bird - I was just thinking that leaving it might be confusing, since you can use the configurator for other firmwares too. I was thinking about changing the theme (or at least the logo) once a specific firmware has been detected.
