### ISSUE TITLE
Remove translations with too many missing translations

### ISSUE THREAD

**Issue by stylesuxx** [stylesuxx/esc-configurator#285]
No need to keep anything in the UI with less than 90% translation progress:
* [x] French
* [x] Turkish

**Comment by psicho100pro** [comment]
Hi, are you interested in a Czech translation?

**Comment by stylesuxx** [comment]
@psicho100pro of course! Added Czech as an option on [crowdin](https://crowdin.com/project/esc-configuratorcom). If you ping me in the esc-configurator Discord, I will add you to the translator group.
