### ISSUE TITLE
ESC Flash Stalled Out Half Way Through ESC 1 On Brand New Quad

### ISSUE THREAD

**Issue by pmeguess** [stylesuxx/esc-configurator#307]
Brand new GEPRC Smart 35. I have two of these. The first one flashed just fine. The second one stalled out about half way through on ESC 1 and failed. Tried again, same thing. I will attach the debug/log file and a screenshot. 
[esc-configurator-log.txt](https://github.com/stylesuxx/esc-configurator/files/10213434/esc-configurator-log.txt)
<img width="932" alt="Screenshot_20221212_060906" src="https://user-images.githubusercontent.com/120431969/207203887-494fb58c-fe24-4f8c-9194-f99a30163f4f.png">

**Comment by stylesuxx** [comment]
Are you sure the battery is fully charged?

**Comment by pmeguess** [comment]
Yes, 4S battery started at 4.0v per cell, now still showing 3.9v per cell.

**Comment by stylesuxx** [comment]
Your radio is off?

**Comment by stylesuxx** [comment]
Does not matter, this is just a sign that the flash went wrong (and is displayed wrongly). Could you please attach the log after attempting to flash again? Your log only contains the initial failed flash, no?

**Comment by stylesuxx** [comment]
Very mysterious. Could you please try with BF 4.2.x? (Dump your settings so you have something to come back to).

**Comment by pmeguess** [comment]
The flash back to BF 4.2 stalled and then failed as well. I need to double check my drivers and reboot the FC board from scratch. This will take awhile.... I'll be back.....

**Comment by stylesuxx** [comment]
At this point I would try different machines and different USB cables...

**Comment by pmeguess** [comment]
Problem solved, my data cable failed. Bought a new USB data cable and everything flashed like it was supposed to, Betaflight and ESC-Configurator. 
Thanks so much for your help!
Paul

**Comment by stylesuxx** [comment]
Yay, happy to hear. Ditch that cable, you don't need something like this in your life ;-)
