### ISSUE TITLE
ESC's Not Being Read

### ISSUE THREAD

**Issue by RussellPinks** [stylesuxx/esc-configurator#316]
I have a SucceX-D F7 Stack (50A 4-in-1 ESC) and it reads perfectly fine in BLHeliS (Firmware BLHeli 32.8). When I come to connect in esd-configurator it see's the motors but after pressing 'Read Settings' the log shows that it can't read any of my ESC's.

![Screenshot 2023-01-13 at 22 45 13](https://user-images.githubusercontent.com/122650218/212433029-7fbdc5d5-6f15-4967-a807-59f33b309a47.png)

**Comment by stylesuxx** [comment]
That's a BLHeli_32 ESC, it's not supported by esc-configurator
