### ISSUE TITLE
speedy bee f405 v3 BLS 4in1 stack (missing escs)

### ISSUE THREAD

**Issue by nukeproof89** [stylesuxx/esc-configurator#326]
hey everyone

I'm attempting to flash my quad to bluejay or if anything just update my firmware for esc. this is a new build quad and my first.

the program cannot find esc2 but did manage to flash all 3 others just fine. I then kept reflashing and now i've lost esc 4 too 
any advice or help would be much appreciated and thanks in advance.

[esc-configurator-log.txt](https://github.com/stylesuxx/esc-configurator/files/10711829/esc-configurator-log.txt)

**Comment by stylesuxx** [comment]
The lost ESC 4 is not reflected in the log. From the beginning there were only 3 ESCs found. Were you able to spin all 4 motors out of the box? Your radio was disabled during reading?

Did you flash a new BF version? If so, are you 100% sure you flashed the correct target? Could be that something with the resources is messed up. I would reset everything to stock state as it was when you took it out of the box.

FOor the future: It's always good to first check your components. an AIO were only 3/4 ESCs show up, I would return immediately.

**Comment by nukeproof89** [comment]
esc 4 is back online now, think maybe a low battery had turned it off as I recharged it and its back. I'm still having a error on motor 3 which just says unknown and sometimes I have 2 esc3 tab windows which say unknown.

I honestly couldnt tell you if it was working out of the box or not now as Ive just completely lost myself in this for a few hours.

yes I i flashed bf first to latest version but I did back up original settings for fc before doing this. should I roll back in betaflight?

thanks for the responses

**Comment by nukeproof89** [comment]
I've managed to sort it now. but thank you for the reply

**Comment by stylesuxx** [comment]
If it shows unknown, you can flash over it, just check the "Ignore MCU Layout" checkbox.

**Comment by stylesuxx** [comment]
> I've managed to sort it now. but thank you for the reply

So what was the solution? Just for others that might run into the same problem.

**Comment by nukeproof89** [comment]
rechecked the rainbow connector. and then inside betaflight changed the protocol from dshot300 back do dsm and this allowed all the motors to spin. reset the quad and then esc could find the missing esc 2.
i also used the ignore mcu layout to flash the 2 unknown escs. 

thanks for the input mate
