### ISSUE TITLE
Cannot connect to matek H743 wing, saying Port already in use by another application - try re-connecting

### ISSUE THREAD

**Issue by lotsofone** [stylesuxx/esc-configurator#327]
**Describe the bug**
When I press connect, it says "Port already in use by another application - try re-connecting"

**Screenshots**
![image](https://user-images.githubusercontent.com/35299440/218627956-0d1683c5-59d7-4343-937b-e0dad0a4e596.png)

**Log**
```
2023-02-14 @ 10:59:27 -- Port already in use by another application - try re-connecting
2023-02-14 @ 10:59:26 -- Opened serial port
2023-02-14 @ 10:59:25 -- Port selected
2023-02-14 @ 10:59:22 -- Port already in use by another application - try re-connecting
2023-02-14 @ 10:59:21 -- Opened serial port
2023-02-14 @ 10:59:18 -- Port selected
2023-02-14 @ 10:59:08 -- Plugged in
2023-02-14 @ 10:59:08 -- Chrome (109.0.0.0) on Windows
```

**Desktop (please complete the following information):**
 - OS: Win11
 - Browser chrome
 - Version 109.0.0.0

**Additional context**
It is okay to connect and flash ESC by Matek F405-WMN, but not okay by Matek H743 wing.
I noticed that Matek H743 wing has 2 com ports when connected to PC.
![image](https://user-images.githubusercontent.com/35299440/218628322-07f405e5-005a-410c-9abf-5c73e9423d90.png)

While Matek F405-WMN only has one.
![image](https://user-images.githubusercontent.com/35299440/218628300-566b791f-17fa-4008-a7c3-aba622254faa.png)

Could this be the reason?

**Comment by stylesuxx** [comment]
So, when selecting the port, do multiple com ports show up? The message usually means that some other application is claiming the serial port.

Make sure that no other configurator is running and close all other apps that might be claiming the serial port. Cura for example is known to do that...

**Comment by lotsofone** [comment]
When I plug in the controller without battery, it first shows up COM5
![image](https://user-images.githubusercontent.com/35299440/218681190-44d0fc41-20b7-4350-b029-ee234d4fe181.png)
Then comes COM6 and COM7, and COM5 disappers
![image](https://user-images.githubusercontent.com/35299440/218681292-7613ad94-1e8b-44f3-8125-d1df44e9e084.png)
Both the two ports give the same error "Port already in use".
I am pretty sure there is no others claiming the port, because I can connect to FC with MP later.

**Comment by stylesuxx** [comment]
Not entirely sure what could be going on here - I would assume that the first one is the bootloader device that disappears ofter some time. Not sure why there then would be two serial devices. You are running ardupilot on this FC, right? You can connect with the original BLHeli_S configurator?

Please also post output of `chrome://device-log/` - clear it first, then attach the flight controller and post a screenshot of the output.

**Comment by lotsofone** [comment]
Yes I am running ardupilot on my FCs. I didn't try original BLHeli_S configurator, only tried the web one. I can connect to the ESC through Matek F405-WMN FC, but cannot through Matek H743 Wing FC.
When I plug in the Matek H743 Wing without battery, the log is
![image](https://user-images.githubusercontent.com/35299440/218708319-25193355-e4e8-42b5-8615-6c72146e2c0d.png)

For Matek F405-WMN, the log is
![image](https://user-images.githubusercontent.com/35299440/218708111-3613a308-45dd-466b-bf8b-e4e865562aa5.png)

**Comment by stylesuxx** [comment]
Hmm, yeah - can't see an issue there. Try the original BLHeli_S configurator please and see if you can connect with that.

You have the same ardupilot versions on both FCs I assume?

**Comment by lotsofone** [comment]
Both FCs have Plane 4.3.3
Is this the original configurator? https://github.com/blheli-configurator/blheli-configurator/releases/tag/1.2.0
It can connect to Matek F405-WMN, can't connect to Matek H743 Wing.
The error message is a little different.
![image](https://user-images.githubusercontent.com/35299440/218739050-7b532085-0032-4b33-aad1-ce94f2ee8012.png)

**Comment by stylesuxx** [comment]
Well, then it's not an issue of the configurator, you will have to ask Matek or Ardupilot how you are intended to connect to the ESCs.

**Comment by stylesuxx** [comment]
Cool, then please report your findings to ardupilot, maybe they can fix it.
