### ISSUE TITLE
Bluejay 16.5 (Beta) error 

### ISSUE THREAD

**Issue by MoonKIE666** [stylesuxx/esc-configurator#350]
I installed the 16.5 Bluejay firmware beta version a while back and now my esc don't want to reflash. I have tried it with all programmers: Blheli_suite, Blheli Configurator, JazzMaveric Configurator...
In all when I try to flash I get an error that says that version 16.5 (Beta) is not recognized and does not flash the esc.
![photo_2023-03-20_21-54-36](https://user-images.githubusercontent.com/16765270/226463646-370189ed-1baf-4855-b775-4dc9c919485d.jpg)

**Comment by stylesuxx** [comment]
That's rather strange - on the bottom right you should have a "Flash all" button. Could you please send a full screenshot?

**Comment by MoonKIE666** [comment]
![image](https://user-images.githubusercontent.com/16765270/226465688-c7cc99a0-ae10-4d03-9ba7-d09ed2c5881a.png)


> That's rather strange - on the bottom right you should have a "Flash all" button. Could you please send a full screenshot?

**Comment by stylesuxx** [comment]
yeah, so - flash all and install some current version of Bluejay ;-)

**Comment by MoonKIE666** [comment]
![image](https://user-images.githubusercontent.com/16765270/226465934-7769e894-18c1-44bf-8f8a-fe1acbfcfae3.png)
When I try to flash them the options are grayed out, the spits a few times and then it turns off and everything stays gray

**Comment by stylesuxx** [comment]
post the log please. Button on the bottom left.

**Comment by MoonKIE666** [comment]
Here I send you the debug log.
[esc-configurator-log (6).txt](https://github.com/stylesuxx/esc-configurator/files/11023080/esc-configurator-log.6.txt)

**Comment by MoonKIE666** [comment]
I don't understand much of all this, but I think there is a problem here.

![image](https://user-images.githubusercontent.com/16765270/226466765-6db395db-e636-4032-8b00-36fec1f8cc5d.png)

**Comment by stylesuxx** [comment]
Yeah, something very strange is going on here... - you have a battery plugged in, right?
Could be that your ESCs are write protected for some reason. Could you tell me which ESCs those are?

Worst case you can try re-flashing via C2 interface.

**Comment by MoonKIE666** [comment]
Yes, I have them with the battery on and the transmitter off. I have many quads and I have never had this problem in all the time I have flashed esc. These ESCs in particular, are those of a TINYHAWK 1, are included within the EMAX fc AIO:

https://emaxmodel.com/collections/tinyhawk-s-parts/products/emax-tinyhawk-s-indoor-drone-part-aio-flight-controller-vtx-receiverYes, I have them with the battery on and the transmitter off. I have many quads and I have never had this problem in all the time I have flashed esc. These ESCs in particular, are those of a TINYHAWK 1, are included within the EMAX fc AIO:

https://emaxmodel.com/collections/tinyhawk-s-parts/products/emax-tinyhawk-s-indoor-drone-part-aio-flight-controller-vtx-receiver

**Comment by stylesuxx** [comment]
Yeah, to me this looks like you initially had Bluejay on, but then reflashed with BLHeli_S and something there went wrong and probably write locked the MCUs. If they are working, I would simply leave them as they are. Recovery via C2 interface will probably be a pain on this AIO.

**Comment by MoonKIE666** [comment]
Nothing, I've also tried it after installing Betaflight 4.4 and no luck. This time I tried a different installer, JazzMaverik, and it gives me the same problem. I have also tried it in the ESC Configurator and nothing. Envío los dos logs

[esc-configurator-log (7).txt](https://github.com/stylesuxx/esc-configurator/files/11023271/esc-configurator-log.7.txt)
[Log JazzMaverik.txt](https://github.com/stylesuxx/esc-configurator/files/11023273/Log.JazzMaverik.txt)

**Comment by stylesuxx** [comment]
Yeah, most likely (at least) the bootloader is corrupt...

C2 will be your only way out at this point: https://oscarliang.com/flash-blheli-c2-interface/

**Comment by stylesuxx** [comment]
Any update on this? Did you try recovery via C2 interface?

**Comment by stylesuxx** [comment]
Closed due to inactivity.
