### ISSUE TITLE
One motor spinning the wrong way, cant change. Reverts back!

### ISSUE THREAD

**Issue by MikeKC3OVL** [stylesuxx/esc-configurator#370]
Armattan 30A BLHeli S to Bluejay 19 motor direction flash is not working. Reverts back when read.

**Comment by stylesuxx** [comment]
you change direction and then click write settings, correct? Sounds like you are clicking the "flash firmware" button instead.

**Comment by MikeKC3OVL** [comment]
Yes, Sorry I missed it write settings. I was doing exactly what you stated. Thank you!
