### ISSUE TITLE
ESCs of MAMBAF722_2022B can not be read

### ISSUE THREAD

**Issue by cgieske01** [stylesuxx/esc-configurator#408]
[esc-configurator-log.txt](https://github.com/stylesuxx/esc-configurator/files/12388298/esc-configurator-log.txt)

**Comment by damosvil** [comment]
Please, could you let us know the esc manufacturer and model?

**Comment by cgieske01** [comment]
sure sorry.
The FC is: Diatone MAMBA F740 AIO 40A 6S 32bit WIFI

(I'm using Crome on MacOS.)

**Comment by damosvil** [comment]
That AIO has Blheli32 escs. Unfortunatelly they are not supported by
esc-configurator.com

You may need to use Blheli32 suite to configure them

**Comment by cgieske01** [comment]
okay! Thanks for your fast reply ;)
