### ISSUE TITLE
Error: UnknownPlatformError: Unknown platform: Neither SiLabs nor Arm

### ISSUE THREAD

**Issue by sliksoft** [stylesuxx/esc-configurator#415]
Hi i am trying to flash speedybee f7 v3 ESC to Bluejay but this is not working for me, can somebody tell me what is wrong?
Everything works fine, motors just work.

2023/09/20 23:51:09: Trying to read 4 ESCs
2023/09/20 23:51:09: ESC 1 read settings failed Unknown platform: Neither SiLabs nor Arm UnknownPlatformError: Unknown platform: Neither SiLabs nor Arm
2023/09/20 23:51:09: Error: UnknownPlatformError: Unknown platform: Neither SiLabs nor Arm 
2023/09/20 23:51:09: Failed reading ESC 1
2023/09/20 23:51:10: ESC 2 read settings failed Unknown platform: Neither SiLabs nor Arm UnknownPlatformError: Unknown platform: Neither SiLabs nor Arm
2023/09/20 23:51:10: Error: UnknownPlatformError: Unknown platform: Neither SiLabs nor Arm 
2023/09/20 23:51:10: Failed reading ESC 2
2023/09/20 23:51:10: ESC 3 read settings failed Unknown platform: Neither SiLabs nor Arm UnknownPlatformError: Unknown platform: Neither SiLabs nor Arm
2023/09/20 23:51:10: Error: UnknownPlatformError: Unknown platform: Neither SiLabs nor Arm 
2023/09/20 23:51:10: Failed reading ESC 3
2023/09/20 23:51:10: ESC 4 read settings failed Unknown platform: Neither SiLabs nor Arm UnknownPlatformError: Unknown platform: Neither SiLabs nor Arm
2023/09/20 23:51:10: Error: UnknownPlatformError: Unknown platform: Neither SiLabs nor Arm 
2023/09/20 23:51:10: Failed reading ESC 4

**Comment by stylesuxx** [comment]
That's BLHeli_32 - use their configurator.
