### ISSUE TITLE
esc not detected

### ISSUE THREAD

**Issue by alexovitch16** [stylesuxx/esc-configurator#417]
HI!

 after a failed flash on esc configurator esc1 doesn't appear in esc configuration website and standalone app. I' ve tried on BLHeli suite and others forks of BLheli and flash Esc 1but the flash is impossible...Have you got any solution for that?
thank you,

here is esc-configurator message:

The amount of available ESCs does not match what the flight controller is reporting. This can have multiple reasons:
The ESC was not ready yet. This can for example happen if it is playing a melody. Also a previous flash could have gone wrong and it needs longer to boot up than usual.
There are simply not more ESCs connected.
The MCU of the ESC is defective.
Try a different USB cable - sometimes they are not properly shielded and might result in such errors.
Make sure your radio is turned off while interacting with the configurator. Switched on radios have been reported to cause issues with electro-magnetic interference and thus failed read/writes.
If the result is not what you are expecting, try clicking the 'Read Settings' button again.

**Comment by stylesuxx** [comment]
If the ESC does not show up, you will have to recover via C2 interface, see here: https://github.com/bird-sanctuary/bluejay/wiki/Unbrick-ESC

**Comment by alexovitch16** [comment]
thanks for the reply, I was afraid about that solution because my FC is the f4 1s 5a v2.2 which no has c2 pad... After I post my question I find that post with the same FC, see the last post, it could be tricky  😅 https://github.com/jflight-public/jesc-configurator/issues/25

Thanks you !

**Comment by stylesuxx** [comment]
Oh yeah - with that one it's going to get tricky I am afraid.

Good Luck!

**Comment by Wasee045** [comment]
> HI!
> 
> after a failed flash on esc configurator esc1 doesn't appear in esc configuration website and standalone app. I' ve tried on BLHeli suite and others forks of BLheli and flash Esc 1but the flash is impossible...Have you got any solution for that? thank you,
> 
> here is esc-configurator message:
> 
> The amount of available ESCs does not match what the flight controller is reporting. This can have multiple reasons: The ESC was not ready yet. This can for example happen if it is playing a melody. Also a previous flash could have gone wrong and it needs longer to boot up than usual. There are simply not more ESCs connected. The MCU of the ESC is defective. Try a different USB cable - sometimes they are not properly shielded and might result in such errors. Make sure your radio is turned off while interacting with the configurator. Switched on radios have been reported to cause issues with electro-magnetic interference and thus failed read/writes. If the result is not what you are expecting, try clicking the 'Read Settings' button again.

Have you got solution
