### ISSUE TITLE
Layout Revision 206 Not Yet Supported

### ISSUE THREAD

**Issue by Nikonrikam** [stylesuxx/esc-configurator#437]
What is the deal with this error? I have been flashing these ESC's with this site for months now and today I get a failed flash and have no idea why. 

![image](https://github.com/stylesuxx/esc-configurator/assets/155192813/fc4d03e7-040f-40ae-ac92-598af432547b)

I am flashing Bluejay, O-H-5, Version 19.2 like I have done before. I use this to swap between 24kHz and 48kHz tunes. I even tried Version 18 of Bluejay and got the same error. 

The FC is flashed to Betaflight 4.4.3.

Thanks,
Sean

**Comment by Nikonrikam** [comment]
https://flywoo.net/products/goku-versatile-f411-vtx

This is the AIO FC I am using.

**Comment by Nikonrikam** [comment]
[esc-configurator-log (2).txt](https://github.com/stylesuxx/esc-configurator/files/13795836/esc-configurator-log.2.txt)
[esc-configurator-log (1).txt](https://github.com/stylesuxx/esc-configurator/files/13795837/esc-configurator-log.1.txt)
[esc-configurator-log.txt](https://github.com/stylesuxx/esc-configurator/files/13795838/esc-configurator-log.txt)
My debug logs.

**Comment by stylesuxx** [comment]
Flash failed on ESC1. Re-flash using the "ignore MCU layout" checkbox and you should be fine.

**Comment by stylesuxx** [comment]
Closed due to inactivity.
