### ISSUE TITLE
Add Russian translation

### ISSUE THREAD

**Issue by stylesuxx** [stylesuxx/esc-configurator#445]

**Comment by stylesuxx** [comment]
@i3ananx - deployed on develop: https://develop.esc-configurator.com/ - can you please check in context?

For everyone down-voting, what's your problem? Speak up if you have an issue. Way to go encouraging people to contribute to an open source project, makes me really want continue pouring my time into this...

**Comment by stylesuxx** [comment]
Please only translate via crowdin, otherwise syncing up will result in a complete mess :-/

**Comment by i3ananx** [comment]
Ok, I’ll make all my changes in via crowdin

**Comment by stylesuxx** [comment]
Merged into develop
