### ISSUE TITLE
flash esc

### ISSUE THREAD

**Issue by Hasselfpv** [stylesuxx/esc-configurator#451]
When trying to flash the esc with Bluejay with 0.19.2 the following error occurs: Layout revision 206 is not yet supported

**Comment by stylesuxx** [comment]
Which ESC?

**Comment by Hasselfpv** [comment]
its the iflight Blitz Mini E55S 4-in-1 2-6s ESC , try with macbook and windows. Only esc1 the other went fine.

**Comment by Hasselfpv** [comment]
> Which ESC?

its the iflight Blitz Mini E55S 4-in-1 2-6s ESC , try with macbook and windows. Only esc1 the other went fine.

**Comment by stylesuxx** [comment]
That's very strange - this is a BLHeli_32 ESC. Please link me to the product page.

**Comment by stylesuxx** [comment]
Interesting. If only one failed to flash but is still showing up in the configurator as "Unknown" you can re-flash it. Just check "Ignore MCU layout" checkbox and select the correct layout yourself.

Please post the log if you have any other issues.

**Comment by Hasselfpv** [comment]
> Interesting. If only one failed to flash but is still showing up in the configurator as "Unknown" you can re-flash it. Just check "Ignore MCU layout" checkbox and select the correct layout yourself.
> 
> Please post the log if you have any other issues.
Thanks, I'll try it later or tomorrow morning and report back

**Comment by Hasselfpv** [comment]
> Interesting. If only one failed to flash but is still showing up in the configurator as "Unknown" you can re-flash it. Just check "Ignore MCU layout" checkbox and select the correct layout yourself.
> 
> Please post the log if you have any other issues.

Now with the check box selected its still work , big thanks for your help.

**Comment by Hasselfpv** [comment]
Now i want to enable RPM Filtering , motors are spinning in mo
<img width="1302" alt="Bildschirm­foto 2024-01-23 um 08 02 42" src="https://github.com/stylesuxx/esc-configurator/assets/122967528/b39708cc-d244-45b7-bfb6-34b59ba18ae6">
tor test , but two of them show error rate

**Comment by stylesuxx** [comment]
Hey, that's not really an esc-configurator issue. I suggest you hip on the BF discord and try to get help there. I would just check how the error rate behaves if you spin the motors up (without props of course and not full throttle).
