### ISSUE TITLE
https://esc-configurator.com/

### ISSUE THREAD

**Issue by fmaccherozzi** [stylesuxx/esc-configurator#453]
I am trying to connect to an ECD3 openpilot controller. It is recognised by the port selector:

![usb selector](https://github.com/stylesuxx/esc-configurator/assets/97107802/af6c396f-6a57-47a4-b7e8-16afb6ac0c30)

However I get the following error "2024-01-31 @ 21:18:39 -- Port already in use by another application - try re-connecting"

![Screenshot 2024-01-31 211934](https://github.com/stylesuxx/esc-configurator/assets/97107802/36dd9df5-55a9-42d0-bfc4-25b35a20d63c)

Is there anythin I can do to connect to the ECD3 controller?

**Comment by stylesuxx** [comment]
If it does not support Betaflight pass-through then not.
