### ISSUE TITLE
Failed to read 4 escs'

### ISSUE THREAD

**Issue by Ajith-Kalyan** [stylesuxx/esc-configurator#456]
I have F722 Mamba stack, I have been trying to access the esc but failed to read them. I have tried different pc's laptops and different cables and browsers, yet couldn't. Below is the log file. Help much appreciated.

2024/02/05 19:39:43: Chrome (121.0.0.0) on Windows
2024/02/05 19:39:44: Failed fetching files for Bluejay
2024/02/05 19:39:44: Chrome (121.0.0.0) on Windows
2024/02/05 19:39:44: Plugged in
2024/02/05 19:39:53: Port selected
2024/02/05 19:39:55: Opened serial port
2024/02/05 19:39:55: MultiWii API version received: 1.45.0
2024/02/05 19:39:55: Flight controller info, identifier: BTFL version: 4.4.3
2024/02/05 19:39:55: Running firmware released on: Nov 14 2023 16:30:12
2024/02/05 19:39:55: Board: S7X2, version: 0
2024/02/05 19:39:55: Unique device ID received - 0x04e00203431510232313835
2024/02/05 19:40:08: Trying to read 4 ESCs
2024/02/05 19:40:10: Failed processing command cmd_DeviceInitFlash after 5 retries. 
2024/02/05 19:40:10: MessageNotOkError: Message not OK 
2024/02/05 19:40:10: Failed reading ESC 1
2024/02/05 19:40:11: ESC 2 read settings failed Unknown platform: Neither SiLabs nor Arm UnknownPlatformError: Unknown platform: Neither SiLabs nor Arm
2024/02/05 19:40:11: Error: UnknownPlatformError: Unknown platform: Neither SiLabs nor Arm 
2024/02/05 19:40:11: Failed reading ESC 2
2024/02/05 19:40:11: ESC 3 read settings failed Unknown platform: Neither SiLabs nor Arm UnknownPlatformError: Unknown platform: Neither SiLabs nor Arm
2024/02/05 19:40:11: Error: UnknownPlatformError: Unknown platform: Neither SiLabs nor Arm 
2024/02/05 19:40:11: Failed reading ESC 3
2024/02/05 19:40:11: ESC 4 read settings failed Unknown platform: Neither SiLabs nor Arm UnknownPlatformError: Unknown platform: Neither SiLabs nor Arm
2024/02/05 19:40:11: Error: UnknownPlatformError: Unknown platform: Neither SiLabs nor Arm 
2024/02/05 19:40:11: Failed reading ESC 4
2024/02/05 19:40:12: Closed port
2024/02/05 19:41:22: Unplugged
2024/02/05 19:41:26: Plugged in
2024/02/05 19:41:36: Port selected
2024/02/05 19:41:39: Opened serial port
2024/02/05 19:41:39: MultiWii API version received: 1.45.0
2024/02/05 19:41:39: Flight controller info, identifier: BTFL version: 4.4.3
2024/02/05 19:41:39: Running firmware released on: Nov 14 2023 16:30:12
2024/02/05 19:41:39: Board: S7X2, version: 0
2024/02/05 19:41:39: Unique device ID received - 0x04e00203431510232313835
2024/02/05 19:41:58: Trying to read 4 ESCs
2024/02/05 19:42:00: Failed processing command cmd_DeviceInitFlash after 5 retries. 
2024/02/05 19:42:00: MessageNotOkError: Message not OK 
2024/02/05 19:42:00: Failed reading ESC 1
2024/02/05 19:42:01: ESC 2 read settings failed Unknown platform: Neither SiLabs nor Arm UnknownPlatformError: Unknown platform: Neither SiLabs nor Arm
2024/02/05 19:42:01: Error: UnknownPlatformError: Unknown platform: Neither SiLabs nor Arm 
2024/02/05 19:42:01: Failed reading ESC 2
2024/02/05 19:42:01: ESC 3 read settings failed Unknown platform: Neither SiLabs nor Arm UnknownPlatformError: Unknown platform: Neither SiLabs nor Arm
2024/02/05 19:42:01: Error: UnknownPlatformError: Unknown platform: Neither SiLabs nor Arm 
2024/02/05 19:42:01: Failed reading ESC 3
2024/02/05 19:42:01: ESC 4 read settings failed Unknown platform: Neither SiLabs nor Arm UnknownPlatformError: Unknown platform: Neither SiLabs nor Arm
2024/02/05 19:42:01: Error: UnknownPlatformError: Unknown platform: Neither SiLabs nor Arm 
2024/02/05 19:42:01: Failed reading ESC 4

**Comment by stylesuxx** [comment]
Mamba F722 Stack is BLHeli_32 - which is not supported.
