### ISSUE TITLE
BetaFPV Meteor75 - ESC 1: **FLASH*FAILED**

### ISSUE THREAD

**Issue by kolorszczak** [stylesuxx/esc-configurator#459]
I have a issue on ESC 1 while trying to flash Bluejay 96kHz:

"**FLASH*FAILED** wersja '0.19' (Layout 206) nie jest jeszcze obsługiwana."

[dump (1).zip](https://github.com/stylesuxx/esc-configurator/files/14508567/dump.1.zip)

**Comment by stylesuxx** [comment]
Please attach the log.

Technically you should be able to just flash over this ESC by selecting the correct layout and checking the "Ignore MCU layout box".

**Comment by kolorszczak** [comment]
That did work. Thanks
