### ISSUE TITLE
ÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿ version '16.7' (Layout 33) is not yet supported.

### ISSUE THREAD

**Issue by bendyna** [stylesuxx/esc-configurator#461]
I've connected SpeedyBee F405 V3 stack + 4 motors (TMotor Velox V2207.5 V2 Veloce Series V1950) to esc-configurator. First I've tried to control all manually via slider, all 4 worked. Then I've pressed "Read setting" and it showed ESC1 as Unknown and all others were correctly identified. I re-connected and after some time ESC1 and ESC3 were unknown. I flashed firmware to all 4 ESCs, 2 were successful and for Unknowns nothing happened (see below log). 
In manual mode they ESC2 and ESC4 now properly work while ESC1 and ESC3 wiggle (only if I put slider to max)

![Screenshot from 2024-04-06 12-35-12](https://github.com/stylesuxx/esc-configurator/assets/1828791/9ca47441-4ff2-498c-9fd0-9488e63b8fcd)

**Log**
```
2024-04-06 @ 12:24:41 -- Flashed ESC 1 - 0.1s
2024-04-06 @ 12:24:41 -- Layout mismatch, override not enabled - aborted
2024-04-06 @ 12:24:41 -- Flashing ESC 1
```

**Comment by stylesuxx** [comment]
If it came like that out of the box, I would have personally returned it. Anyway, check the "ignore MCU layout" checkbox and flash the two unknown ones with the correct firmware.

**Comment by bendyna** [comment]
@stylesuxx Thanks a lot, that helped!

For others who can encounter this, checkbox appears after you press "Flash Firmware" on any ESC

**Comment by syaeither** [comment]
а что если не помогает флажок? и не возможно перепрошить?

**Comment by stylesuxx** [comment]
@syaeither English please.

**Comment by syaeither** [comment]
what if the checkbox doesn't work? and it's not possible to reflash?

**Comment by stylesuxx** [comment]
Then you will have to flash via C2 interface. Does the ESC not show up at all when your read them? Post a log please.
