### ISSUE TITLE
モーターのdirectionをreverse できなくしてしまいました。

### ISSUE THREAD

**Issue by ichyaro** [stylesuxx/esc-configurator#464]
お世話になります。機体のMODELが,HAPPY MODELのMOBULA8 ELRS2.4GHZです。
モーターのdirectionが、normalだったので、reverseに成功していましたが、normaiに戻ってしまいました。
ESC のターゲットがZ-H-30.です。.ESC-1,2,3のVersionを0.19.２へフラッシュできません。
ESC-1　 UNKOWN
ESC-2 　UNKOWN
ESC-3 　UNKPWN
ESC-4　Z-H-30 - ブルージェイ、0.19、48kHz
となります。よく理解しないで、フラッシュしたのが、良くなかったです。

よろしくご指導お願いいたします。

sc-configurator-log.txt](https://github.com/stylesuxx/esc-configurator/files/15209516/esc-configurator-log.txt)

**Comment by stylesuxx** [comment]
English please. It seems. something during flashing went wrong. Make sure your batteries are fully charged and flash again, checking the "Ignore MCU Layout" checkbox - make sure to select the correct layout manually.

**Comment by ichyaro** [comment]
You want to reverse the direction of the motor, and you were able to successfully reverse it with BLHELI-S. 2024年5月4日 20:59、Chris L. ***@***.***>からのメール： English please. It seems. something during flashing went wrong. Make sure your batteries are fully charged and flash again, checking the "Ignore MCU Layout" checkbox - make sure to select the correct layout manually. — Reply to this email directly, view it on GitHub , or unsubscribe . You are receiving this because you authored the thread. Message ID: ***@***.***>

**Comment by ichyaro** [comment]
I apologize for not speaking English earlier. Please excuse my poor English. You are receiving this because you authored the thread.You want to reverse the direction of the motor, and you were able to successfully reverse it with BLHELI-S. I recently spun in the yaw direction, so this time I tried to flash it using BLUEJAY version 1.3.7. The Bluejay configurator will no longer be maintained. Please use https://esc-configurator.com/ for future updates. I flashed the ESC firmware using the online version, but ESC 1, ESC2: and esc3: are: unknown. ESC 4 is z-H-30 - Blue Jay, 0.19, 48kHz This ESC version '0.14' (layout 203) is not yet supported.It becomes.It seems that the esc has been damaged. Do you have any predictions to solve this problem? 2024年5月4日 22:41、古木一郎 ***@***.***>からのメール： 2024年5月4日 20:59、Chris L. ***@***.***>からのメール： English please. It seems. something during flashing went wrong. Make sure your batteries are fully charged and flash again, checking the "Ignore MCU Layout" checkbox - make sure to select the correct layout manually. — Reply to this email directly, view it on GitHub , or unsubscribe . You are receiving this because you authored the thread. Message ID: ***@***.***>

**Comment by stylesuxx** [comment]
No worries. As mentioned before - you need to reflash, selecting the target manually. and checking the "Ignore MCU layout" checkbox. Make sure your batteries are fully charged and probably use a different USB cable than the one that lead to the failed flash.

**Comment by ichyaro** [comment]
Thank you very much for your guidance. I didn't do what I was told and caused damage to the FC due to my own selfish actions. There are two reasons for the failure. One is compatible with 1S-2S Lipo/LIHV batteries, but I accidentally connected a 3S Lipo/LIHV battery. My computer can no longer be turned on. I took it to a shop right away, had it diagnosed, removed the battery, and it started up. Second, the esc specifications are BLHeliSuite programmable. Support firmware Target: Z_H_30 Default protocol: DSHOT300 Bluejay firmware It was supported. But be warned: the code memory will be erased. However, in BLHeliSuite, do you want to flash target esc#1 unknown esc (unknown layout) to :z-H-30(MULTI)BLHELI REV:16.7? I checked "Yes" . This is the number one factor that causes undesirable results. In light of this failure, if you are not confident, do not flash ESC, ask others for Heip and wait for advice. However, thanks to the checkbox "Do you want to ignore inappropriate MCUs and layouts?", I was able to find out. This was a valuable achievement, so I am very grateful. I will continue to work hard on the ESC program so that I can fly the drone without giving up. 2024年5月6日 0:46、Chris L. ***@***.***>からのメール： No worries. As mentioned before - you need to reflash, selecting the target manually. and checking the "Ignore MCU layout" checkbox. Make sure your batteries are fully charged and probably use a different USB cable than the one that lead to the failed flash. — Reply to this email directly, view it on GitHub , or unsubscribe . You are receiving this because you authored the thread. Message ID: ***@***.***>
