### ISSUE TITLE
 Port already in use by another application - try re-connecting (AM32 ESC via USB serial linker)

### ISSUE THREAD

**Issue by florianverhein** [stylesuxx/esc-configurator#483]
I'm attempting to connect to an AM32 ESC (SEQURE SQESC 12100) via a USB linker (uses ch340) [available here](https://www.amazon.com/Linker-Compatible-Brushless-Control-Programming/dp/B0CCXGFSB3/ref=asc_df_B0CCXGFSB3/?tag=hyprod-20&linkCode=df0&hvadid=692875362841&hvpos=&hvnetw=g&hvrand=13936190944545780409&hvpone=&hvptwo=&hvqmt=&hvdev=c&hvdvcmdl=&hvlocint=&hvlocphy=9199035&hvtargid=pla-2281435177138&psc=1&mcid=b31d53a33a3b3b219b9f6c499bf55387&hvocijid=13936190944545780409-B0CCXGFSB3-&hvexpln=73&gad_source=1).

It correctly shows up as a usb serial device in port selection. It also shows as paired once connected.

However whenever I click the green USB "connect" button I get the "Port already in use" error, every time. 
I see no options to specify e.g. AM32 etc in case thats relevant. 

Oddly, I get the same error when its not plugged in, so I imagine the error is not very specific. 

I've tried restarting, uninstalling the latest ch340 drivers (https://www.wch-ic.com/downloads/CH341SER_ZIP.html) and restarting, which resulted in what seem to be osx built in drivers being used, disconnecting port, etc.
I plug the linker in with power already to ESC.

Currently:
```
florian$ ls tty.usb*
tty.usbserial-1410
```
I don't have any programs other programs running other than a few basic ones (Finder, Preview etc). I have no flight controller software installed as I don't use it. The only program that would make use of usb serial is the Arduino IDE, which is not running. 

Example log. Extended logging and advanced debugging options did not give any further info. 

```
2024-08-21 @ 14:07:37 -- Port already in use by another application - try re-connecting
2024-08-21 @ 14:07:37 -- Opened serial port
2024-08-21 @ 14:04:52 -- Port already in use by another application - try re-connecting
2024-08-21 @ 14:04:52 -- Opened serial port
2024-08-21 @ 14:04:50 -- Plugged in
2024-08-21 @ 14:04:50 -- Chrome (127.0.0.0) on Mac OS
```

I'm on OSX 11.7.10, Chrome browser.

**Comment by stylesuxx** [comment]
AM32 have their own configurator, please use that: https://am32.ca
