### ISSUE TITLE
ESC Power Rating setting could have better UX

### ISSUE THREAD

**Issue by Aulma** [stylesuxx/esc-configurator#484]
**Is your feature request related to a problem? Please describe.**
This might be picky, but the ESC Power Rating setting could have better UX. I initially set my SuperX HD ESC to 1S, thinking it was correct since I'm using 1S packs. I experienced occasional startup power issues with motors not spinning up. After a long time, I read the tooltip, changed the setting to 2S, and immediately resolved the problem.

**Describe the solution you'd like**
When selecting 1S it could show some kind of small red text stating something like "1-2S ESC should configure 2S+".

**Describe alternatives you've considered**
The dropdown could also show those 3 options with the 2nd and 3rd option both ultimately mapped to the same configuration in the background:
"1S",  "1-2S",  "2S+"

![chrome_V0C4TyjArI](https://github.com/user-attachments/assets/051ac87c-b929-45b7-a991-e4367e52065b)

Very thankful though and this is definitely no priority stuff!

**Comment by stylesuxx** [comment]
I think this setting is tricky without reading the info bubble. But you are right, maybe a third option would make it more intuitive - I am just not a big fan of options that are not really options...

Thank you for your feedback in any case.

**Comment by Aulma** [comment]
> I think this setting is tricky without reading the info bubble. But you are right, maybe a third option would make it more intuitive - I am just not a big fan of options that are not really options...

I think my first "solution" would be indeed cleaner, to just show a small warning when selecting 1S. Even if it is just saying: "check the tooltip/hint".

**Comment by pfeerick** [comment]
Perhaps?
- 1S Only
- 1-2S+

Since 2S+ is simply wrong if it encapsulates 1S 🤭

**Comment by stylesuxx** [comment]
2S+ never encapsulates pure 1S boards. But I get your point.

So far I like your suggested options most.

**Comment by stylesuxx** [comment]
Merged into develop will be part of the next release, thanks again for feedback.
