### ISSUE TITLE
Min/max Default values

### ISSUE THREAD

**Issue by stylesuxx** [stylesuxx/esc-configurator#486]
A user on discord reported that restoring defaults sets min Startup Power above max startup power on Bluejay.

**EDIT:**
Restoring defaults will set min/max incorrectly. This needs to be adjusted to match up Bluejay defaults.

**Comment by TGS78** [comment]
on my Z-H-30 with 0.21.0 or 0.21.1 RC1 the default for min. startup power is still above max. start power
min default is 1025
max default is 1020

**Comment by stylesuxx** [comment]
Even if you reset to default values?

**Comment by TGS78** [comment]
yes, when I press "Restore Default Settings" in ESC Web Configurator it always goes back to 1025/1020.
I can also check with some other ESCs if you want.

**Comment by stylesuxx** [comment]
Ah, wait a minute, this is currently not released. It should work on the develop version though: https://develop.esc-configurator.com/

Could you confirm?

**Comment by TGS78** [comment]
Yes it works on the develop version :)
Sorry for the "false alarm"

**Comment by stylesuxx** [comment]
No worries - good reminder to release a new version. There are a couple other things I want to get done first though...
