### ISSUE TITLE
cant flash to bluejay on SpeedyBee F7 V3

### ISSUE THREAD

**Issue by ced4568** [stylesuxx/esc-configurator#487]
2024/08/29 11:50:59: Closed port
2024/08/29 11:51:31: Unplugged
2024/08/29 11:51:34: Plugged in
2024/08/29 11:52:00: Opened serial port
2024/08/29 11:52:00: MultiWii API version received: 1.46.0
2024/08/29 11:52:00: Flight controller info, identifier: BTFL version: 4.5.1
2024/08/29 11:52:00: Running firmware released on: Jul 27 2024 04:00:33
2024/08/29 11:52:00: Board: S7X2, version: 0
2024/08/29 11:52:00: Unique device ID received - 0x04d00333133511437333432
2024/08/29 11:52:04: Trying to read 4 ESCs
2024/08/29 11:52:07: Failed processing command cmd_DeviceInitFlash after 5 retries. 
2024/08/29 11:52:07: MessageNotOkError: Message not OK 
2024/08/29 11:52:07: Failed reading ESC 1
2024/08/29 11:52:07: ESC 2 read settings failed Unknown platform: Neither SiLabs nor Arm UnknownPlatformError: Unknown platform: Neither SiLabs nor Arm
2024/08/29 11:52:07: Error: UnknownPlatformError: Unknown platform: Neither SiLabs nor Arm 
2024/08/29 11:52:07: Failed reading ESC 2
2024/08/29 11:52:07: ESC 3 read settings failed Unknown platform: Neither SiLabs nor Arm UnknownPlatformError: Unknown platform: Neither SiLabs nor Arm
2024/08/29 11:52:07: Error: UnknownPlatformError: Unknown platform: Neither SiLabs nor Arm 
2024/08/29 11:52:07: Failed reading ESC 3
2024/08/29 11:52:07: ESC 4 read settings failed Unknown platform: Neither SiLabs nor Arm UnknownPlatformError: Unknown platform: Neither SiLabs nor Arm
2024/08/29 11:52:07: Error: UnknownPlatformError: Unknown platform: Neither SiLabs nor Arm 
2024/08/29 11:52:07: Failed reading ESC 4
2024/08/29 11:52:17: Trying to read 4 ESCs
2024/08/29 11:52:17: ESC 1 read settings failed Unknown platform: Neither SiLabs nor Arm UnknownPlatformError: Unknown platform: Neither SiLabs nor Arm
2024/08/29 11:52:17: Error: UnknownPlatformError: Unknown platform: Neither SiLabs nor Arm 
2024/08/29 11:52:17: Failed reading ESC 1
2024/08/29 11:52:18: ESC 2 read settings failed Unknown platform: Neither SiLabs nor Arm UnknownPlatformError: Unknown platform: Neither SiLabs nor Arm
2024/08/29 11:52:18: Error: UnknownPlatformError: Unknown platform: Neither SiLabs nor Arm 
2024/08/29 11:52:18: Failed reading ESC 2
2024/08/29 11:52:18: ESC 3 read settings failed Unknown platform: Neither SiLabs nor Arm UnknownPlatformError: Unknown platform: Neither SiLabs nor Arm
2024/08/29 11:52:18: Error: UnknownPlatformError: Unknown platform: Neither SiLabs nor Arm 
2024/08/29 11:52:18: Failed reading ESC 3
2024/08/29 11:52:18: ESC 4 read settings failed Unknown platform: Neither SiLabs nor Arm UnknownPlatformError: Unknown platform: Neither SiLabs nor Arm
2024/08/29 11:52:18: Error: UnknownPlatformError: Unknown platform: Neither SiLabs nor Arm 
2024/08/29 11:52:18: Failed reading ESC 4
2024/08/29 11:52:29: Closed port
2024/08/29 11:53:34: Chrome (128.0.0.0) on Windows
2024/08/29 11:53:34: Plugged in
2024/08/29 11:53:34: TOPICS: Topics blocker loaded 
2024/08/29 11:53:34: injection-tss TSS: hosted page injected 
2024/08/29 11:53:34: injection-tss MBTSS: Nonce:  a1o0hp2md8wjzaao3vqfthcb65bi0xh4glnclujtz77m
2024/08/29 11:53:39: Chrome (128.0.0.0) on Windows
2024/08/29 11:53:39: Plugged in
2024/08/29 11:53:39: TOPICS: Topics blocker loaded 
2024/08/29 11:53:39: injection-tss TSS: hosted page injected 
2024/08/29 11:53:39: injection-tss MBTSS: Nonce:  9ndcivtcpawqxwe7mxcevvjepohwedheyd82mbg0w19
2024/08/29 11:53:40: Opened serial port
2024/08/29 11:53:40: MultiWii API version received: 1.46.0
2024/08/29 11:53:40: Flight controller info, identifier: BTFL version: 4.5.1
2024/08/29 11:53:40: Running firmware released on: Jul 27 2024 04:00:33
2024/08/29 11:53:40: Board: S7X2, version: 0
2024/08/29 11:53:40: Unique device ID received - 0x04d00333133511437333432
2024/08/29 11:53:45: Trying to read 4 ESCs
2024/08/29 11:53:48: Failed processing command cmd_DeviceInitFlash after 5 retries. 
2024/08/29 11:53:48: MessageNotOkError: Message not OK 
2024/08/29 11:53:48: Failed reading ESC 1
2024/08/29 11:53:48: ESC 2 read settings failed Unknown platform: Neither SiLabs nor Arm UnknownPlatformError: Unknown platform: Neither SiLabs nor Arm
2024/08/29 11:53:48: Error: UnknownPlatformError: Unknown platform: Neither SiLabs nor Arm 
2024/08/29 11:53:48: Failed reading ESC 2
2024/08/29 11:53:48: ESC 3 read settings failed Unknown platform: Neither SiLabs nor Arm UnknownPlatformError: Unknown platform: Neither SiLabs nor Arm
2024/08/29 11:53:48: Error: UnknownPlatformError: Unknown platform: Neither SiLabs nor Arm 
2024/08/29 11:53:48: Failed reading ESC 3
2024/08/29 11:53:51: Failed processing command cmd_DeviceInitFlash after 5 retries. 
2024/08/29 11:53:51: MessageNotOkError: Message not OK 
2024/08/29 11:53:51: Failed reading ESC 4

**Comment by stylesuxx** [comment]
Speedybee F7 V3 is Blheli32, not supported by us. Use Blheli32 configurator instead, or better yet, see if you can migrate to AM32.

Good luck.
