### ISSUE TITLE
ESC protocol

### ISSUE THREAD

**Issue by ahhhhdh** [stylesuxx/esc-configurator#489]
The test found that the ESC could not drive the motor when the ESC protocol was modified to PWM

**Comment by stylesuxx** [comment]
Not enough information. Which firmware are you using? If Bluejay, than this is expected since it only supports DSHOT. Also why do you assume this to be a configuration issue?

**Comment by ahhhhdh** [comment]
Thank you for your reply to help me clarify my doubts. As you mentioned, I am using Bluejay because I want to use this ESC brush in Bluejay for fixed wing, so I need PWM protocol driver,

**Comment by stylesuxx** [comment]
Yeah, Bluejay only Support DSHOT. Flash BLHeli_S instead and you should be fine.

**Comment by ahhhhdh** [comment]
Haha, because Bluejay has more editable content
