### ISSUE TITLE
PROBLEM WITH CONECTION

### ISSUE THREAD

**Issue by NovatosDelFpv** [stylesuxx/esc-configurator#492]
PROBLEM WITH CONECTED

[esc-configurator-log.txt](https://github.com/user-attachments/files/17137003/esc-configurator-log.txt)

**Comment by stylesuxx** [comment]
Probably BLHelis32? Please provide proper info or I'll close this issue.

**Comment by NovatosDelFpv** [comment]
If blhelis32 is correct, how could I pass it to bluejay?

**Comment by stylesuxx** [comment]
You can't. Please tell me which ESC you have exactly (link to product page).

**Comment by NovatosDelFpv** [comment]
FOXXER REAPER F4 128k 65A BL32

**Comment by NovatosDelFpv** [comment]
https://www.fpv24.com/es/foxeer/foxeer-reaper-f4-128k-65a-bl32-4in1-fpv-esc

**Comment by stylesuxx** [comment]
Yes that's BLHeli_32. We don't support that. Also it's generally no longer maintained, you can't update that anyway.
See if you can flash AM32, other than that you can use it as it is. Good luck!
