### ISSUE TITLE
Sequre 12200 AM32 No connection

### ISSUE THREAD

**Issue by jimmy6616** [stylesuxx/esc-configurator#498]
From the web link, com5 is appearing in the connection options, constantly getting , '2024-11-09 @ 11:48:39 -- Port already in use by another application - try re-connecting' , re-started the laptop, Win11, same issue. No other usb devices attached

**Comment by stylesuxx** [comment]
AM32 have their own configurator, please use that https://am32.ca

**Comment by jimmy6616** [comment]
Tried that as well , it’s says connected to device , when you click on Configurator and select base it tune nothing happens 
Jim




On Saturday, November 9, 2024, 12:27 PM, Chris L. ***@***.***> wrote:




AM32 have their own configurator, please use that https://am32.ca

**Comment by stylesuxx** [comment]
The "port already in use" message usually means exactly that: some other application is claiming the serial device. Cura for example likes to do that. If in doubt, I would just try on a different computer.
