### ISSUE TITLE
Upgrade esc BLS bluejay to PWM

### ISSUE THREAD

**Issue by Soares493** [stylesuxx/esc-configurator#499]
Friend I purchased an ESC BLS Bluejay 100A to install on a fixed wing, however it does not work with PWM. I would like help to make the settings. How to connect ESC directly to PC without controller?

**Comment by stylesuxx** [comment]
PWM has been deliberately removed from Bluejay. If you need PWM, please run Blheli_S.

**Comment by Soares493** [comment]
Thank you for your attention. 
Do you have any tutorial on how to update the firmware from ESC to BlHeli? How to do this without a controller card, i.e. connect the ESC directly to the PC?

**Comment by stylesuxx** [comment]
You will need a flight controller with BF passthrough, then you can use https://esc-configurator.com

**Comment by Soares493** [comment]
Friend, can you help how to upgrade to Blheli_S ?
