### ISSUE TITLE
AM32 Setting descriptions

### ISSUE THREAD

**Issue by stylesuxx** [stylesuxx/esc-configurator#55]
@AlkaMotors it would be really nice if you could document the AM32 settings [here](https://github.com/stylesuxx/esc-configurator/blob/develop/src/translations/en/hints.json). Just explain a bit what the setting does.

**Comment by AlkaMotors** [comment]
Ok done!, see PR #57

**Comment by AlkaMotors** [comment]
Oh wait there is more from eeprom version 1! , i will add those later today

**Comment by stylesuxx** [comment]
Whoops, was to quick to pull it in - reopened your PR ;-)

**Comment by AlkaMotors** [comment]
its ok, working on it now, just a few minutes

**Comment by stylesuxx** [comment]
Merged and live - thank you.
