### ISSUE TITLE
Display PWM frequency

### ISSUE THREAD

**Issue by stylesuxx** [stylesuxx/esc-configurator#72]
See https://github.com/mathiasvr/bluejay-configurator/commit/2810c8a6d8127fd7dd9dc58de4a4fa1195546d1d

It would be a good idea if the Sources hat a way of returning their own Name String instead of building that in the ESC component.

**Comment by mathiasvr** [comment]
I tried to take a look at this, but I couldn't figure out what would be the preferred way?

**Comment by stylesuxx** [comment]
Oh thanks, but it's done already - I did not push it yet since I wanted to also do it for AM32.
There is now a function for each source that will return a display Name.
