### ISSUE TITLE
Pre commit hook taking too long

### ISSUE THREAD

**Issue by stylesuxx** [stylesuxx/esc-configurator#88]
Accoriding to [this comment](https://github.com/stylesuxx/esc-configurator/pull/86#issuecomment-813125283) the pre commit is taking too long.

@mathiasvr is it really the linter that takes so long, or rather the tests? Linter is done for me in under 5 seconds and the tests are done in under 8. Could you maybe post the error messages? I could move linting and testing to the run before pushing, but I actually like having the confidence to only commit tested stuff.

you can always commit with --no-verify to skip the checks.

**Comment by mathiasvr** [comment]
Ah right it could be the tests running. In vscode there was no indication that the commit had “begun”, so I ended up starting the precommit over and over.

I think it’s good to have the linting on precommit, however the tests I think would be better on prepush, but that’s up to you.

I have a strange workflow where I commit a lot of different things and reorder it later, but that means it’s not always working before I’m done ;-)

**Comment by stylesuxx** [comment]
Yes, I think I will set it up like this since I have the tests watching all the time anyway.
