### ISSUE TITLE
Move the bottom status bar information slightly to the center

### ISSUE THREAD

**Issue by DusKing1** [stylesuxx/esc-configurator#96]
in some new phone like my oneplus8 as we have a round corner, the version info and port info will be cut a little. As shown:

![image](https://user-images.githubusercontent.com/31283897/114254586-df1fe480-99e2-11eb-9857-04b2f5c9fd39.png)

**Comment by stylesuxx** [comment]
Do you know how to remote debug with chrome? It would be cool if you could  tell me how much I need to offset it from the sides.

**Comment by DusKing1** [comment]
ahh I don't know.., but in my case, "Port blabla" need to be moved right about 2 chars and so did the version string

**Comment by stylesuxx** [comment]
I am sure there is also not enough space to display the battery information. Generally it might be a better idea to move all of this into the center and shorten the labels on mobile.

Generally I think mobile needs some adaptations.

**Comment by DusKing1** [comment]
So you decide to move put the battery information also at the bottom bar? I didn't keep a good track of your latest development.

**Comment by stylesuxx** [comment]
Yes.
![Screenshot from 2021-04-10 11-07-15](https://user-images.githubusercontent.com/978192/114264743-f5cb3900-99ec-11eb-91bf-5ce777be1aa0.png)

But I actually might move it into the Motor control box, since I can only read it before connecting to the ESCs anyway.
