### ISSUE TITLE
Flashing error

### ISSUE THREAD

**Issue by mathiasvr** [stylesuxx/esc-configurator#98]
When the firmware file has not been loaded from web, there is time to press the "Flash" button multiple times potentially leading to corruption.
I'm not sure what caused the problem since this also caused strange behavior when disconnecting/connecting and i ultimately had to refresh.

**Comment by stylesuxx** [comment]
By "not loaded from web" you mean flashing a local file? Or do you mean a file that has been loaded from web previously and the cached version was used?

**Comment by mathiasvr** [comment]
W the file has not been cached it takes some time to download it.

**Comment by stylesuxx** [comment]
Yes, good catch - had to throttle my internet to be able to reproduce. Still, it will "only" flash the firmware multiple times. Interesting that you ended up with a broken state.

**Comment by mathiasvr** [comment]
Hm, broken/flash failed only seems to happen when i spam the button a lot.
